version: '3.8'

services:
  app:
    image: node:alpine
    container_name: nestjs_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://mongo:27017/challenge
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  mongo-data:
