# Use the official Node.js image as the base image
FROM node:21-alpine3.18
 
# Create and set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the NestJS application
RUN npm run build

EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start:prod"]