version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '8080:3000'
    expose:
      - '3000'
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    # make env file to .env.docker
    env_file:
      - .env.docker

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  mongo-data:
